eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
#    hostname: clientName
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
      healthcheck:
        enabled: true
      lease:
        duration: 5
    register-with-eureka: true
spring:
  application:
    name: customer-service
